color: null
description: null
fieldLayouts:
  220403af-3cd5-4076-952c-43f8919394da:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-13T12:24:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4eb6aeef-dea6-407b-a9e5-493feac3ee6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-13T12:26:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5dadefd-1251-46bb-a7ed-b3edc1d6dd7a # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5444f0d7-7f47-42b4-a7b7-ca8f4845eb08
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 3ba68b59-dcf3-4746-9f5e-d8861fe41267
        userCondition: null
handle: accordionElement
hasTitleField: true
icon: null
name: Element
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
