allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5a22dabe-28e8-4046-bf48-a370fe78dc5f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-10T13:05:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4fbcf124-58cc-4090-a22c-63e4fb799a69
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faf95099-c09c-47bc-9fc9-82aa39ce1766
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e2354cf6-6b15-447d-877c-395142a2cfc9
        userCondition: null
    thumbFieldKey: null
handle: fileDownload
hasTitleField: false
icon: file
name: Dateidownload
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
