color: null
description: null
fieldLayouts:
  2fb475e7-960b-48af-bb6a-3a532b1f67cf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-13T12:02:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4f49e33-358b-4830-8d71-63597370851e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-13T12:39:25+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c3e5e55a-63e7-493f-960d-515837528ef9
            userCondition: null
          -
            dateAdded: '2025-11-13T12:39:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d771bc7c-2840-499a-9faa-58fab8bfc523 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 688e68e1-66ad-4f79-956c-7e89bcf025f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-13T12:39:25+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 31a26765-b4f7-4e68-9768-ec71d25aa662
            userCondition: null
          -
            dateAdded: '2025-11-13T12:31:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3cd47c1-517c-459b-a604-f474743e83d3 # Inhalt
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28982cef-ef28-4994-b004-1089e4f1682b
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e6caba66-4b7c-4ee8-920d-9b90bd244250
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-13T12:33:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d5aa30a2-0ab9-4cdc-add4-c2be28babceb # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e145e8c-c9fd-40ef-b31b-c8d62232b43a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a457f2c2-e65f-4e50-ae3c-47d8019640a9
        userCondition: null
handle: homepage
hasTitleField: true
icon: null
name: Startseite
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
