color: null
description: null
fieldLayouts:
  cdcecf1c-5985-43b1-bac9-a607c5a94170:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-13T12:03:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 81173713-ea5f-4811-9868-339a071d28b8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-13T12:20:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff163dd2-2671-4a9c-bead-517148786a6d # Überschrift 
            handle: null
            instructions: null
            label: 'Überschrift H1'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 152b929e-0675-49ab-9f77-c208150c990d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-13T12:39:46+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c8574e60-74d6-4d42-a309-b2cee125e442
            userCondition: null
          -
            dateAdded: '2025-11-13T12:39:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d771bc7c-2840-499a-9faa-58fab8bfc523 # Hero
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f19c3e05-90d4-4229-ab7e-39704bc3c130
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-13T12:39:46+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 839f903a-c75a-4eab-9d7a-0cb1470beb5c
            userCondition: null
          -
            dateAdded: '2025-11-13T12:20:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3cd47c1-517c-459b-a604-f474743e83d3 # Inhalt
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e548f86-7c9d-4a43-b1ee-a4d9864fe6e8
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b5c70f47-9d1d-4301-9e1d-b55e26732b04
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-13T12:33:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d5aa30a2-0ab9-4cdc-add4-c2be28babceb # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbb86d90-5f61-4703-b8be-b5bc1e122371
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5d7bda34-a060-4d2f-97a5-614ddb97721e
        userCondition: null
handle: pages
hasTitleField: true
icon: null
name: Seiten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
