color: null
description: null
fieldLayouts:
  6e9e3258-7cff-4e23-a8aa-9426d0056332:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T12:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c558b5d3-3c91-4a45-ac82-58076842eca3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 15e158d2-0bd4-454c-9cf2-f572718c49c6 # Datum
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f205869-6992-492c-98b3-d79b3428337f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 50006a71-71e6-45d9-a0b8-9d1a05cdf281 # Veranstaltungsort
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be1a13ce-b56f-4f21-9992-d71a0aac5b2c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6836b9cd-2b61-4141-894a-38150257c144
            userCondition: null
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 963a5968-e991-4e25-8bb3-3c12f6422098 # Veranstaltungsreihe
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 727ccab8-8ebc-4820-bf28-798dd5832d54
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 400f5962-d8da-4a3a-a54b-32c67077fd86
            userCondition: null
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 30e962cd-8f19-4011-a569-2e6cb25791e8 # Bild
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a1312b5-56e7-4593-8569-0e2ff1543779
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e5dadefd-1251-46bb-a7ed-b3edc1d6dd7a # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66a126e5-3f7c-42bb-b2ff-fbddfca01963
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8d78b155-67db-4c17-8b18-ddba1195ddae # Hinweis
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a832bb12-103b-4a93-b916-80e07b33aa45
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d31d6756-0870-4a8a-b666-12dd6454d0b0
        userCondition: null
handle: termin
hasTitleField: true
icon: calendar
name: Termin
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{eventSeries.one.title ?? "Termin"}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
