color: null
description: null
fieldLayouts:
  a63d83d3-1ef9-40d0-a83a-eb38a06f023e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-03T12:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e56d7bb-ca7d-4f33-9ebd-32142603e251
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 30e962cd-8f19-4011-a569-2e6cb25791e8 # Bild
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d57b23c2-2f21-4426-99ff-ec35b017d9e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-03T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e5dadefd-1251-46bb-a7ed-b3edc1d6dd7a # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 244f80eb-abfe-4042-a44f-5a03c17d87b9
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 26a6f103-baca-47f5-a7ba-e200d9471dc8
        userCondition: null
handle: veranstaltungsreihe
hasTitleField: true
icon: calendar-days
name: Veranstaltungsreihe
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
