altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f03120b8-492d-4c00-a8c6-2818d7e32fa5:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-13T12:13:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 24f04ea9-9bd7-423b-a5e8-751c7d70e13b
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: f0a2839d-cb56-490a-8dc2-05b6b376d76a
        userCondition: null
fs: media
handle: logos
name: Logos
sortOrder: 2
subpath: logos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: media/logos
