altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c295c20d-10ca-45c4-a707-1b47cb61ffcc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-13T12:35:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ec713ce7-44ee-4948-82e7-6b1bd74c0eef
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 764f8777-98b9-4bc6-b504-5454e6b00f0b
        userCondition: null
fs: media
handle: videos
name: Videos
sortOrder: 4
subpath: videos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
