columnSuffix: null
handle: buttons
instructions: null
name: Buttons
searchable: false
settings:
  createButtonLabel: 'Neuer Button'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 23d1a135-c065-4b14-8379-a83af7d8d792 # Button
        -
          - group
          - Allgemein
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
