columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  advancedFields:
    - target
    - title
    - download
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              -
                - 'volume:eaad13fa-ab0b-4a45-af4a-faf401a49a2b' # Downloads
            -
              - allowedKinds
              -
                - image
                - excel
                - pdf
                - powerpoint
                - text
                - captionsSubtitles
                - video
                - word
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - asset
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
