columnSuffix: null
handle: position
instructions: null
name: Ausrichtung
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - left
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Rechts
        -
          - value
          - right
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
