defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 662c794f-dd22-459b-919e-8ac67bb6b931 # Seiten
  -
    uid: 93652fac-d36c-4bfb-a3c8-3c9ea3a0ceb1 # Veranstaltungen
handle: pages
maxAuthors: 1
name: Seiten
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ca499a8e-a51d-4bc8-9ddb-26d3ef6a018f: # cykelbude
    enabledByDefault: true
    hasUrls: true
    template: _pages/default.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 5efa34d6-47e1-406f-8b1e-a17cee80845e
type: structure
