defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: b264a3f5-9d66-4e78-8a0a-3de539c0408a # Einstellungen
handle: settings
maxAuthors: 1
name: Einstellungen
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ca499a8e-a51d-4bc8-9ddb-26d3ef6a018f: # cykelbude
    enabledByDefault: true
    hasUrls: true
    template: einstellungen/_entry.twig
    uriFormat: einstellungen
type: single
